name = "image-proxy"
pages_build_output_dir = "dist"
compatibility_date = "2024-02-24"

# If deploying as a standalone Worker (not Pages)
# main = "api/proxy.ts"

[vars]
NODE_VERSION = "20"

[site]
bucket = "./dist"
